### PR TITLE
[???] operator -> from none(white default) to orange

### PR DESCRIPTION
**Pull request by Z4RX**

### CODE REVIEW

**Comment by Z4RX** [comment]
@sainnhe I faced a problem. In C++ this "arrow" `->` is an operator via documentation. So logically it should be orange.
image
But it will probably overload the total codeflow.
image
So designer verdict is really required.

**Comment by sainnhe** [comment]
When encountering this type of problem, a criterion is "Which choice can be accepted by more people".

This time you can go ahead and choose the design, I don't want to interfere your decision too much.

**Comment by Z4RX** [comment]
Okey.

Anyway I want your advice. C++ syntax looks ugly with lot of mistakes. But default dark+ theme looks ok(not ideal but less mistakes). As i read microsoft work a lot with C++ tokenization and add a lot of new tokens. I'd like to create a new brach and try to optimize C++ syntax. What do you think about it?

**Comment by sainnhe** [comment]
Of course yes! Those file types are only roughly optimized and are guaranteed to basically work, they need more precise optimization.

I think maybe we should notice this in README.

**Comment by Z4RX** [comment]
Yes, that's true, I saw a lot of people blaming themes instead of vscode for C++ syntax.

**Comment by Z4RX** [comment]
I already started to work with C++ syntax and one of the most funny things is that it looks much better without cpp scopes

**Comment by Z4RX** [comment]
@sainnhe Need your help. I'd like to compare vscode and vim themes, does vim need some plugins for C/C++ or it has a good builtin support of syntax?

**Comment by sainnhe** [comment]
The built-in syntax is VERY BAD, it cannot even highlight function name.

Vim users often need to install some additional plugins to get better syntax highlighting support, currently there are 3 types of syntax highlighting plugins:

1. Enhanced syntax files. The traditional way to highlight a scope in vim is writing a syntax file using vim script based on regex, this type of plugins implement a more advanced syntax files.

2. Semantic highlighting provided by language server, just like it is in vscode.

3. Tree-sitter based highlighting. Tree-sitter is a code parsing library, the newest neovim(community fork of vim) integrates tree-sitter api so users can write a tree-sitter based plugin to provide support for syntax highlighting, incremental selection, text object, code completion, etc. IMO, this is the most advanced way to highlight the code. The highlighting is very accurate, and the performance is very high. Unlike semantic highlighting provided by language server which only supports a very limited amount of programming languages, tree-sitter supports almost all of the common programming languages. Unfortunately, looks like MS has no plan to support tree-sitter based highlighting, they are focus on semantic highlighting recently.

**Comment by Z4RX** [comment]
Thanks for information!

**Comment by sainnhe** [comment]
I just rewrote C/C++ highlights https://github.com/sainnhe/gruvbox-material-vscode/commit/0a3463701b9283fd7792d6e6a650e8b5317dce83

Close this since it has been solved.

**Pull request closed without merging**
